version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 3000:8080
    environment:
      DB_URL: mongodb://db/vidly

  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - 3001:8086
    volumes:
      #volumen dentro del container
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=
    links:
      - influxdb
    ports:
      - 3002:3000
    volumes:
      - grafana_data:/var/lib/grafana

#primero hemos definido el volumen antes de poder usarlo
volumes:
  grafana_data: {}
  influxdb_data:  {}
