version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 3000:8080
    environment:
      DB_URL: mongodb://db/vidly
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      #volumen dentro del container
      - vidly:/data/db
#primero hemos definido el volumen antes de poder usarlo
volumes:
  vidly: 